name: Docker Image CI

on:
  push:
    branches: master
    paths:
      - 'Dockerfile'
      - '.github/**.yml'
      - 'startup.sh'
      - 'supervisord-openssh-server.conf'

jobs:
  xampp8:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tomsik68/xampp:8.2.12,tomsik68/xampp:8,tomsik68/xampp:latest
          build-args: XAMPP_URL=https://kumisystems.dl.sourceforge.net/project/xampp/XAMPP%20Linux/8.2.12/xampp-linux-x64-8.2.12-0-installer.run?viasf=1

  xampp7:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tomsik68/xampp:7.4.33,tomsik68/xampp:7
          build-args: XAMPP_URL=https://netix.dl.sourceforge.net/project/xampp/XAMPP%20Linux/7.4.33/xampp-linux-x64-7.4.33-0-installer.run
